"""Initial Supabase migration

Revision ID: a58f71b38f49
Revises: 
Create Date: 2026-09-14 09:11:48.602953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a58f71b38f49'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('admins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('morning_entry_time', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('sections',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('semesters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('batch_name', sa.String(), nullable=False),
    sa.Column('current_year', sa.Integer(), nullable=False),
    sa.Column('current_semester', sa.Integer(), nullable=False),
    sa.Column('sections_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_code', sa.String(length=20), nullable=False),
    sa.Column('subject_name', sa.String(length=200), nullable=False),
    sa.Column('subject_title', sa.String(length=255), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=30), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_code', 'department_id', 'academic_year', 'semester', name='uq_subject_context')
    )
    op.create_index(op.f('ix_subjects_academic_year'), 'subjects', ['academic_year'], unique=False)
    op.create_index(op.f('ix_subjects_department_id'), 'subjects', ['department_id'], unique=False)
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_index(op.f('ix_subjects_semester'), 'subjects', ['semester'], unique=False)
    op.create_index(op.f('ix_subjects_status'), 'subjects', ['status'], unique=False)
    op.create_index(op.f('ix_subjects_subject_code'), 'subjects', ['subject_code'], unique=False)
    op.create_index(op.f('ix_subjects_subject_name'), 'subjects', ['subject_name'], unique=False)
    op.create_index(op.f('ix_subjects_subject_type'), 'subjects', ['subject_type'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teachers_department_id'), 'teachers', ['department_id'], unique=False)
    op.create_index(op.f('ix_teachers_email'), 'teachers', ['email'], unique=True)
    op.create_index(op.f('ix_teachers_employee_id'), 'teachers', ['employee_id'], unique=True)
    op.create_index(op.f('ix_teachers_id'), 'teachers', ['id'], unique=False)
    op.create_index(op.f('ix_teachers_name'), 'teachers', ['name'], unique=False)
    op.create_index(op.f('ix_teachers_status'), 'teachers', ['status'], unique=False)
    op.create_table('attendance_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('teacher_id', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=True),
    sa.Column('department_id', sa.String(), nullable=True),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', name='sessionstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_sessions_id'), 'attendance_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_subject_id'), 'attendance_sessions', ['subject_id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_teacher_id'), 'attendance_sessions', ['teacher_id'], unique=False)
    op.create_table('calendar_overrides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('override_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.String(length=10), nullable=False),
    sa.Column('end_date', sa.String(length=10), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('section_name', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_overrides_department_id'), 'calendar_overrides', ['department_id'], unique=False)
    op.create_index(op.f('ix_calendar_overrides_end_date'), 'calendar_overrides', ['end_date'], unique=False)
    op.create_index(op.f('ix_calendar_overrides_id'), 'calendar_overrides', ['id'], unique=False)
    op.create_index(op.f('ix_calendar_overrides_override_type'), 'calendar_overrides', ['override_type'], unique=False)
    op.create_index(op.f('ix_calendar_overrides_start_date'), 'calendar_overrides', ['start_date'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('roll_no', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=10), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['section'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['semester'], ['semesters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_academic_year'), 'students', ['academic_year'], unique=False)
    op.create_index(op.f('ix_students_batch_id'), 'students', ['batch_id'], unique=False)
    op.create_index(op.f('ix_students_department_id'), 'students', ['department_id'], unique=False)
    op.create_index('ix_students_dept_sem_sec', 'students', ['department_id', 'semester', 'section'], unique=False)
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_name'), 'students', ['name'], unique=False)
    op.create_index(op.f('ix_students_roll_no'), 'students', ['roll_no'], unique=True)
    op.create_index(op.f('ix_students_section'), 'students', ['section'], unique=False)
    op.create_index(op.f('ix_students_semester'), 'students', ['semester'], unique=False)
    op.create_index(op.f('ix_students_status'), 'students', ['status'], unique=False)
    op.create_table('teacher_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.String(length=10), nullable=True),
    sa.Column('day_of_week', sa.String(length=20), nullable=False),
    sa.Column('period_id', sa.String(length=20), nullable=False),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('span', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_assignments_day_of_week'), 'teacher_assignments', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_teacher_assignments_id'), 'teacher_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_assignments_period_id'), 'teacher_assignments', ['period_id'], unique=False)
    op.create_index(op.f('ix_teacher_assignments_section_id'), 'teacher_assignments', ['section_id'], unique=False)
    op.create_index(op.f('ix_teacher_assignments_subject_id'), 'teacher_assignments', ['subject_id'], unique=False)
    op.create_index(op.f('ix_teacher_assignments_teacher_id'), 'teacher_assignments', ['teacher_id'], unique=False)
    op.create_table('timetable_structures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(length=100), nullable=False),
    sa.Column('grid_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_structures_academic_year'), 'timetable_structures', ['academic_year'], unique=False)
    op.create_index(op.f('ix_timetable_structures_batch_id'), 'timetable_structures', ['batch_id'], unique=False)
    op.create_index(op.f('ix_timetable_structures_department_id'), 'timetable_structures', ['department_id'], unique=False)
    op.create_index(op.f('ix_timetable_structures_id'), 'timetable_structures', ['id'], unique=False)
    op.create_index(op.f('ix_timetable_structures_section_name'), 'timetable_structures', ['section_name'], unique=False)
    op.create_index(op.f('ix_timetable_structures_semester'), 'timetable_structures', ['semester'], unique=False)
    op.create_table('attendance_marks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('roll_number', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LEAVE', 'OD', 'HALF_DAY', name='markstatus'), nullable=True),
    sa.Column('method', sa.Enum('BARCODE_SCAN', 'MANUAL_ENTRY', name='scanmethod'), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('marked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_marks_id'), 'attendance_marks', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_marks_session_id'), 'attendance_marks', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendance_marks_student_id'), 'attendance_marks', ['student_id'], unique=False)
    op.create_table('day_wise_attendance',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LEAVE', 'OD', 'HALF_DAY', name='markstatus'), nullable=True),
    sa.Column('method', sa.Enum('BARCODE_SCAN', 'MANUAL_ENTRY', 'AUTO_ROLLUP', name='scanmethod'), nullable=True),
    sa.Column('marked_by', sa.String(), nullable=True),
    sa.Column('marked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['marked_by'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_day_wise_attendance_date'), 'day_wise_attendance', ['date'], unique=False)
    op.create_index(op.f('ix_day_wise_attendance_id'), 'day_wise_attendance', ['id'], unique=False)
    op.create_index(op.f('ix_day_wise_attendance_student_id'), 'day_wise_attendance', ['student_id'], unique=False)
    op.create_table('student_enrollments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.String(length=10), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_enrollments')
    op.drop_index(op.f('ix_day_wise_attendance_student_id'), table_name='day_wise_attendance')
    op.drop_index(op.f('ix_day_wise_attendance_id'), table_name='day_wise_attendance')
    op.drop_index(op.f('ix_day_wise_attendance_date'), table_name='day_wise_attendance')
    op.drop_table('day_wise_attendance')
    op.drop_index(op.f('ix_attendance_marks_student_id'), table_name='attendance_marks')
    op.drop_index(op.f('ix_attendance_marks_session_id'), table_name='attendance_marks')
    op.drop_index(op.f('ix_attendance_marks_id'), table_name='attendance_marks')
    op.drop_table('attendance_marks')
    op.drop_index(op.f('ix_timetable_structures_semester'), table_name='timetable_structures')
    op.drop_index(op.f('ix_timetable_structures_section_name'), table_name='timetable_structures')
    op.drop_index(op.f('ix_timetable_structures_id'), table_name='timetable_structures')
    op.drop_index(op.f('ix_timetable_structures_department_id'), table_name='timetable_structures')
    op.drop_index(op.f('ix_timetable_structures_batch_id'), table_name='timetable_structures')
    op.drop_index(op.f('ix_timetable_structures_academic_year'), table_name='timetable_structures')
    op.drop_table('timetable_structures')
    op.drop_index(op.f('ix_teacher_assignments_teacher_id'), table_name='teacher_assignments')
    op.drop_index(op.f('ix_teacher_assignments_subject_id'), table_name='teacher_assignments')
    op.drop_index(op.f('ix_teacher_assignments_section_id'), table_name='teacher_assignments')
    op.drop_index(op.f('ix_teacher_assignments_period_id'), table_name='teacher_assignments')
    op.drop_index(op.f('ix_teacher_assignments_id'), table_name='teacher_assignments')
    op.drop_index(op.f('ix_teacher_assignments_day_of_week'), table_name='teacher_assignments')
    op.drop_table('teacher_assignments')
    op.drop_index(op.f('ix_students_status'), table_name='students')
    op.drop_index(op.f('ix_students_semester'), table_name='students')
    op.drop_index(op.f('ix_students_section'), table_name='students')
    op.drop_index(op.f('ix_students_roll_no'), table_name='students')
    op.drop_index(op.f('ix_students_name'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_index('ix_students_dept_sem_sec', table_name='students')
    op.drop_index(op.f('ix_students_department_id'), table_name='students')
    op.drop_index(op.f('ix_students_batch_id'), table_name='students')
    op.drop_index(op.f('ix_students_academic_year'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_calendar_overrides_start_date'), table_name='calendar_overrides')
    op.drop_index(op.f('ix_calendar_overrides_override_type'), table_name='calendar_overrides')
    op.drop_index(op.f('ix_calendar_overrides_id'), table_name='calendar_overrides')
    op.drop_index(op.f('ix_calendar_overrides_end_date'), table_name='calendar_overrides')
    op.drop_index(op.f('ix_calendar_overrides_department_id'), table_name='calendar_overrides')
    op.drop_table('calendar_overrides')
    op.drop_index(op.f('ix_attendance_sessions_teacher_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_subject_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_id'), table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    op.drop_index(op.f('ix_teachers_status'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_name'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_employee_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_email'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_department_id'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_subjects_subject_type'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_subject_name'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_subject_code'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_status'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_semester'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_department_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_academic_year'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_table('batches')
    op.drop_table('semesters')
    op.drop_table('sections')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    op.drop_table('academic_years')
    # ### end Alembic commands ###
